layout_spectrum: 0.9084414
typography_spectrum: 0.09076262
color:
  saturation: 0.9049408
  brandStrength: 0.1669211
  lightness: 0.5161117
  rhythmicContrast: 0.7180451
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: The Hanks-Frazer Page
